name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pyinstaller PyQt5 matplotlib
      - name: Build EXE
        run: |
          pyinstaller --windowed --onefile --name "GoatedStudyTracker" goatedstudytracker.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: GoatedStudyTracker-exe
          path: dist/GoatedStudyTracker.exe
